name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to the latest version
    - name: Setup Go
      uses: actions/setup-go@v2 # Update to the latest version
      with:
          go-version: 1.20
    - name: Run tests core
      run: ./run_tests.sh
